services:
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: triplanner-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - triplanner-mongo-config:/data/configdb
      - triplanner-mongo-db:/data/db
    networks:
      - red-mongo-triplanner
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: triplanner-mongo-express
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mi-mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    networks:
      - red-mongo-triplanner
    ports:
      - "8081:8081"

volumes:
  triplanner-mongo-config:
  triplanner-mongo-db:

networks:
  red-mongo-triplanner:
